node {
   stage('Preparation') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"                        
     def commit_id = readFile('.git/commit-id').trim()
   }
   stage('test') 
     nodejs(nodeJSInstallationName: 'cbr-nodejs') {
       sh 'npm install --only=dev'
       sh 'npm test'
     }
   }
   stage('docker build/push') {
     def commit_id = readFile('.git/commit-id').trim()
     sh "echo ${commit_id}"
     docker.withRegistry('https://index.docker.io/v1/', 'dockerhub') {
       def app = docker.build("cbrwick/cheers2019:${commit_id}", '.').push()
     }
   }


